apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  schedulerName: doslab-gpu-scheduler
  containers:
  - image: tensorflow/tensorflow:1.15.2-gpu-py3
    name: tf
    command: ["sh", "-c", "curl -s https://lsalab.cs.nthu.edu.tw/~ericyeh/KubeShare/demo/mnist.py | python3 -"]
    resources:
      limits:
        doslab.io/gpu-memory: 818
        doslab.io/gpu-core: 80
    volumeMounts:
    - mountPath: /kubeshare/library
      name: lib
  volumes:
  - name: lib
    hostPath:
      path: /kubeshare/library
      type: Directory